<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @see \Magento\Paypal\Block\Express\Review\Details
 * @var \Magento\Paypal\Block\Express\Review\Details $block
 */
// svea-checkout_cart id is mandatory (it's used into ajax update blocks part)

?>
<div id="svea-checkout_cart" class="table-wrapper order-items">
    <table id="details-table" class="svea-checkout-review" cellspacing="0" cellpadding="0" border="0">
        <thead>
        <tr>
            <th class="col item-img" scope="col">
                <span><?= /* @escapeNotVerified */
                    __('Item') ?></span>
            </th>
            <th class="col item-desc" scope="col">
                <span><?= /* @escapeNotVerified */
                    __('Description') ?></span>
            </th>
            <th class="col qty" scope="col">
                <span><?= /* @escapeNotVerified */
                    __('Quantity') ?></span>
            </th>
            <th class="col price" scope="col">
                <span><?= /* @escapeNotVerified */
                    __('Price') ?></span>
            </th>
            <th class="col price" scope="col">
                <span><?= /* @escapeNotVerified */
                    __('Subtotal') ?></span>
            </th>
        </tr>
        </thead>
        <tbody class="svea-checkout-cart svea-checkout-item">
        <?php foreach ($block->getItems() as $item): ?>
            <?php echo $block->getItemHtml($item) ?>
        <?php endforeach ?>
        </tbody>
    </table>
    <div id="svea_cart_extra">
        <div id="svea_coupon_toggle">
            <?php if($block->showCouponCode()): ?>

                <div class="fieldset comment">
                <input type="checkbox" name="coupon-toggle" value="1" id="coupon-toggle"
                       title="<?php echo __('Use coupon'); ?>" class="checkbox">
                <label for="coupon-toggle"><?php echo __('Do you have a coupon code?'); ?>
                    <span><?= __('Click here to enter code')?> </span></label>
            </div>
            <?php endif;?>

        </div>
        <?php echo $block->getChildHtml('newsletter'); ?>
    </div>
    <div id="svea-checkout_cart_totals">
        <table cellspacing="0" cellpadding="0" border="0">
            <tfoot>
            <?php echo $block->getChildHtml('totals'); ?>
            </tfoot>
        </table>
    </div>
</div>