<?php
// @codingStandardsIgnoreFile
$subscribe = $block->subscribeNewsletter();

?>
<div id="svea-checkout_newsletter" class="svea-checkout-block newsletter">
    <?php $customerComment = $block->getQuote()->getCustomerNote(); ?>
    <form method="post" action="<?php echo $block->getNewsletterSubmitUrl(); ?>"
          id="svea-checkout-newsletter-form">
        <div class="fieldset comment">
            <input type="checkbox" name="newsletter" value="<?php echo $subscribe ? '1' : '0'; ?>" <?php echo $subscribe ? 'checked="checked"' : ''; ?>
                   id="newsletter" title="<?php echo __('Sign Up for Our Newsletter') ?>" class="checkbox"/>
            <label for="newsletter"><span class="tick"></span> <?php echo __('Sign Up for Our Newsletter') ?></label>
        </div>
    </form>
</div>