<?php


// @codingStandardsIgnoreFile
/** @var $block \Svea\Checkout\Block\Checkout */

//id  #svea-checkout_shipping_method is mandatory
$quote = $block->getQuote();
if($quote->isVirtual()) return;

?>
<div id="svea-checkout_shipping_address">
    <!-- 
    <?php
        $sa = $quote->getShippingAddress();
        echo "PostCode: {$sa->getPostcode()}, Country: {$sa->getCountryId()}\n";
     ?>
     -->
</div>
