<?php
/**
 * @var \Magento\Sales\Block\Adminhtml\Order\AbstractOrder $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */

/** @var \Magento\Shipping\Helper\Data $shippingHelper */
$shippingHelper = $block->getData('shippingHelper');
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');

/** @var \Svea\Checkout\ViewModel\Adminhtml\Order\View\Shipping $viewModel */
$viewModel = $block->getViewModel();

$order = $block->getOrder();
$locationInfo = $viewModel->getShippingLocationInfo($order);
$addressBlock = $block->getChildBlock('address');

?>
<?php if ($order->getIsVirtual()):
    return '';
endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= $escaper->escapeHtml(__('Shipping &amp; Handling Information')) ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()): ?>
            <p>
                <a href="#" id="linkId" title="<?= $escaper->escapeHtmlAttr(__('Track Order')) ?>">
                    <?= $escaper->escapeHtml(__('Track Order')) ?>
                </a>
            </p>
            <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                'onclick',
                "popWin('" . $escaper->escapeJs($shippingHelper->getTrackingPopupUrlBySalesModel($order)) .
                "','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')",
                'a#linkId'
            ) ?>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <p>
                <strong><?= $escaper->escapeHtml($order->getShippingDescription()) ?></strong>

                <?php if ($taxHelper->displayShippingPriceIncludingTax()): ?>
                    <?php $excl = $block->displayShippingPriceInclTax($order); ?>
                <?php else: ?>
                    <?php $excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                <?php endif; ?>
                <?php $incl = $block->displayShippingPriceInclTax($order); ?>

                <?= /** @noEscape */ $excl ?>
                <?php if ($taxHelper->displayShippingBothPrices() && $incl != $excl): ?>
                    (<?= $escaper->escapeHtml(__('Incl. Tax')) ?> <?= /** @noEscape */ $incl ?>)
                <?php endif; ?>
            </p>
            <?php if ($locationInfo->getName()): ?>
                <p><strong><?= $escaper->escapeHtml($locationInfo->getName()) ?></strong></p>
            <?php endif; ?>
            <?php if ($addressBlock): ?>
                <?= $addressBlock->toHtml() ?>
            <?php endif; ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('No shipping information available')) ?>
        <?php endif; ?>
    </div>
</div>
