<?php

// @codingStandardsIgnoreFile
$couponCode = $block->getCouponCode() ?? '';
?>
<div id="svea-checkout_coupon" class="svea-checkout-block discount">
    <div class="svea-checkout-title" data-role="title">
        <h4 id="svea-checkout-review-heading" role="heading" aria-level="2">
            <?php echo $block->escapeHtml(__('Coupon Code')) ?>
        </h4>
    </div>
        <form id="discount-coupon-form"
              action="<?php /* @escapeNotVerified */ echo $block->getCouponSubmitUrl() ?>"
              method="post"
              >
            <div class="fieldset coupon<?php strlen($couponCode) ? ' applied' : ''?>">
                <input type="hidden" name="remove" id="remove-coupon" value="<?php echo strlen($couponCode) ? 1 : 0;?>" />
                <div class="field">
                    <div class="control">
                        <input type="text" class="svea-checkout-show-on-focus input-text" id="coupon_code" name="coupon_code" value="<?php echo $block->escapeHtml($couponCode) ?>" placeholder="<?php echo $block->escapeHtml(__('Enter discount code'));?>" />
                    </div>
                </div>
                <div class="actions-toolbar">
                    <?php if (!strlen($couponCode)): ?>
                        <div class="primary">
                            <button class="action apply primary" type="submit" value="<?php /* @escapeNotVerified */ echo __('Apply Discount') ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Apply Discount') ?></span>
                            </button>
                        </div>
                    <?php else: ?>
                        <div class="secondary">
                            <button  type="submit" class="action cancel primary" value="<?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?>"><span><?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?></span></button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </form>
</div>